site_name: Emaflix
site_url: "https://example.com/"
nav:
  - Home: index.md
  - Documentação: 
      - Visão Geral do Produto: "visão do produto.md"
      - Visão Geral do Projeto: "visão do projeto.md"
    
theme: 
  name: material
  features:
  - navigation.tabs
  - navigation.section
  - toc.integrate
  - navigation.top
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  language: pt-BR
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Modo Dark
      primary: green
      accent: red
  plugins:
  - glightbox

  
