name: Continuos Integration

on:
  push:
  pull_request:

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    
    steps:
      - uses: actions/checkout@v2
 

     
      - name: run install dependecies frontend and run
        run: |
          cd Emaflix/Frontend
          npm install
          npm run dev &
          sleep 10
          pkill -f "npm run dev"

      - name: Run tests
        run: |
          cd Emaflix/Backend_node
          npm test
