name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Run install dependencies and start frontend
        run: |
          cd Emaflix/Frontend
          npm install
          npm run dev &
          sleep 10
          pkill -f "npm run dev"

      - name: Run tests
        run: |
          cd Emaflix/Backend_node
          npm test
