name: Continuos Integration

on:
  push:
  pull_request:

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - name: run install dependecies frontend and run
        run: |
          cd Emaflix
          npm install
          npm run dev &
          sleep 10
          pkill -f "npm run dev"
